// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Number struct {
	ID     pgtype.UUID `json:"id"`
	Number int32       `json:"number"`
}
