// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const getAllNumbersSorted = `-- name: GetAllNumbersSorted :many
SELECT id, number
FROM numbers
ORDER BY number ASC
`

func (q *Queries) GetAllNumbersSorted(ctx context.Context) ([]Number, error) {
	rows, err := q.db.Query(ctx, getAllNumbersSorted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Number{}
	for rows.Next() {
		var i Number
		if err := rows.Scan(&i.ID, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNumber = `-- name: InsertNumber :one
INSERT INTO numbers (number)
VALUES ($1)
RETURNING id, number
`

func (q *Queries) InsertNumber(ctx context.Context, number int32) (Number, error) {
	row := q.db.QueryRow(ctx, insertNumber, number)
	var i Number
	err := row.Scan(&i.ID, &i.Number)
	return i, err
}
