// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

// CreateNumberResponse defines model for CreateNumberResponse.
type CreateNumberResponse struct {
	Numbers *Numbers `json:"numbers,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Numbers defines model for Numbers.
type Numbers = []int

// AddNumberParams defines parameters for AddNumber.
type AddNumberParams struct {
	// Number The number to add
	Number int `form:"number" json:"number"`
}
